### PR TITLE
add a Project file

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by vchuravy** [comment]
Time to drop 0.6 from CI?

**Comment by KristofferC** [comment]
Ok, dropped 0.6 compat.

**Comment by KristofferC** [comment]
@ararslan, maybe you could deploy this?

**Comment by ararslan** [comment]
I've retuned the benchmarks, which I think is all that's needed (IIRC). So it should be "deployed" now, I guess.

**Comment by KristofferC** [comment]
Alright, let's try.

**Pull request merged**
