### PR TITLE
Add benchmark for collect with Union eltype

### PR DESCRIPTION
**Pull request by nalimilan**
Covers https://github.com/JuliaLang/julia/pull/30480.

### CODE REVIEW

**Comment by nalimilan** [comment]
The CI failure on 0.6 seems unrelated. Any ideas?

**Comment by ararslan** [comment]
It's pretty clear that there will be no more 0.6 releases at this point, so I'd say it's safe to ignore 0.6 errors on CI until we remove it from CI. I'll open an issue to track removal of 0.6 stuff.

**Comment by ararslan** [comment]
#246

**Comment by nalimilan** [comment]
CI is green now. Good to merge at last? :-)

**Pull request merged**
