### PR TITLE
Update params.json

### PR DESCRIPTION
**Pull request by christopher-dG**
Hoping that I did this right 🙃

### CODE REVIEW

**Comment by ararslan** [comment]
Can you tell me what the steps were you did to get this? I'm guessing you did it right, but I'm not sure how else to review a PR for an insane JSON file. :stuck_out_tongue:

**Comment by christopher-dG** [comment]
I just ran `retune.sh` on node6. I can paste the contents of that here tomorrow morning.

**Comment by christopher-dG** [comment]
```sh
#!/bin/sh

set -x -e

cd "${HOME}/julia"
git checkout master
git fetch origin --prune
git reset --hard origin/master
git prune
git gc
git clean -fdx
make -j4 USECCACHE=1 USE_BINARYBUILDER_LLVM=0

cd "${HOME}/packages/BaseBenchmarks"
git checkout master
git fetch origin --prune
git reset --hard origin/master

${HOME}/julia/julia -e 'using Pkg; Pkg.update(); Pkg.add("BenchmarkTools")'
${HOME}/julia/julia -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()))'
${HOME}/julia/julia ./etc/tune.jl
```

Seems pretty legit

**Comment by ararslan** [comment]
Then just copied the params file to node 5, then locally for a PR?

**Comment by christopher-dG** [comment]
Yep exactly.

**Review by ararslan — APPROVED** [review]
Perfect! You can sync the `nanosoldier` branch on master once this is merged.

**Pull request merged**
