### PR TITLE
Add Math benchmarks category

### PR DESCRIPTION
**Pull request by simonbyrne**
Currently only exponent functions, mostly @musm's recent PRs in Base.

### CODE REVIEW

**Comment by jrevels** [comment]
Thanks! This seems like it should be a new group (maybe named `exponentiation`?) in the `ScalarBenchmarks` module instead of a new module.

**Comment by simonbyrne** [comment]
sure, no problem

**Comment by simonbyrne** [comment]
done

**Comment by musm** [comment]
great, thanks!

**Comment by simonbyrne** [comment]
Thanks, let me know when it is ready on nanosoldier

**Pull request merged**
