### PR TITLE
Remove dependence on partial linear indexing

### PR DESCRIPTION
**Pull request by mbauman**
Needed to test performance of https://github.com/JuliaLang/julia/pull/21750.

### CODE REVIEW

**Comment by mbauman** [comment]
Looks like I'll need to also update Compat...

**Comment by mbauman** [comment]
This is now awaiting https://github.com/JuliaLang/Compat.jl/pull/399.

**Comment by ararslan** [comment]
You can bump Compat to 0.31.0 once https://github.com/JuliaLang/METADATA.jl/pull/10949 is merged.

**Comment by ararslan** [comment]
I've bumped the Compat dependency for you, but this will now need #107 in order to pass CI.

**Comment by ararslan** [comment]
I'm retuning the Nanosoldier benchmarks now, and I'll trigger a new Nanosoldier run on your PR once that's done.

**Pull request merged**
