### PR TITLE
Offer master to the Nanosoldier

### PR DESCRIPTION
**Pull request by ararslan**
He hungers for commits

### CODE REVIEW

**Comment by jrevels** [comment]
Did the parameters get retuned here, i.e. do the new benchmarks have the correct evaluations-per-sample setting? (sorry I was late on the review)

**Comment by ararslan** [comment]
Not yet. The retuning job should be done on Nanosoldier now so I'll copy it over and submit a PR for that.

**Comment by jrevels** [comment]
Cool beans. For future reference, any new benchmarks merged into the `nanosoldier` branch should be paired with updated parameters in the same merge - otherwise those benchmarks are essentially "wrong" and could result in Nanosoldier reporting spurious timings.

**Comment by ararslan** [comment]
Oh good to know, I didn't realize that. Sorry!!

**Pull request merged**
