### PR TITLE
modern vectorization of nbody_vec

### PR DESCRIPTION
**Pull request by stevengj**
A more "modern" version of nbody_vec using dot operators and fusion (in 0.6).   Also, `sum(x .^ 2)` should really be `sumabs2(x)` in performance-sensitive code.

### CODE REVIEW

**Comment by stevengj** [comment]
Thanks @jrevels.  How long will it be before nanosoldier benchmarks use the new version?

**Comment by jrevels** [comment]
The tuning process is running now, so they should be ready in an hour or two. I'll post here when it's finished.

**Comment by stevengj** [comment]
Thanks!

**Comment by jrevels** [comment]
@Sacha0 @stevengj The benchmarks from #47, #46, and #45 are now runnable on Nanosoldier.

**Pull request merged**
