### PR TITLE
fix deprecation in sumabs2 etc

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by tkelman** [comment]
guess if we ever need to benchmark 0.4 again we can do so on a branch?

**Comment by jrevels** [comment]
Thanks, @KristofferC!

> guess if we ever need to benchmark 0.4 again we can do so on a branch?

The only thing that would break on 0.4 here is `maximum(abs, ...)`, right? Maybe we can just wrap the definition of that one in a version check?

**Comment by tkelman** [comment]
I think that signature would work on 0.4, but be a slower baseline than maxabs because function arguments don't work as well on 0.4

**Comment by KristofferC** [comment]
Wrap everything in a version check?

**Comment by jrevels** [comment]
Ah, it does work (I only checked the documentation...and the Travis build passed as well which should've tipped me off 😛). I'm okay with losing `maxabs`benchmarks etc. on v0.4. 

> Wrap everything in a version check?

It's up to you if you want to go for it, this LGTM as is.

**Comment by KristofferC** [comment]
Sounds good to me.

**Pull request merged**
