### PR TITLE
Sincos

### PR DESCRIPTION
**Pull request by pkofod**
Well, why not add some more benchmarks! ref: https://github.com/JuliaLang/julia/pull/22824

### CODE REVIEW

**Comment by pkofod** [comment]
Uhm, sincos is not defined on earlier versions. Should I just introduce `sincos(x) = (sin(x), cos(x))` ?

**Comment by jrevels** [comment]
> Should I just introduce sincos(x) = (sin(x), cos(x))?

Probably better to just wrap the code in a conditional on the `VERSION`.

**Comment by pkofod** [comment]
Should be gtg now I believe

**Comment by ararslan** [comment]
Any further comments, @jrevels?

**Comment by jrevels** [comment]
LGTM. Thanks again!

**Comment by ararslan** [comment]
Cool beans. I'll retune and trigger Nanosoldier on your PR.

**Pull request merged**
