### PR TITLE
backwards compatible fix for recent xor change in Base

### PR DESCRIPTION
**Pull request by jrevels**
ref [today's daily build](https://github.com/JuliaLang/julia/commit/80770e955906c8cdbcfaf2ea73ed772195429aad#commitcomment-19824380) and  JuliaLang/julia@2751493abfae6ffe6b833b06c7950887a9379fbc

### CODE REVIEW

**Comment by StefanKarpinski** [comment]
How about adding the definition to Compat.jl instead and upgrading that?

**Comment by jrevels** [comment]
> How about adding the definition to Compat.jl instead and upgrading that?

Actually, I just realized that a `xor` fix was added to Compat.jl a couple of days ago (quite speedy!) so I've switched to using that.

**Comment by tkelman** [comment]
Do we still need this BenchmarkTools upper bound?

**Comment by jrevels** [comment]
Yes, BaseBenchmarks can't use a newer BenchmarkTools until Nanosoldier is updated to use the BenchmarkTools serialization wrapper. I should put that same bound should be on Nanosoldier as well.

**Pull request merged**
